Check build directory

diff --git a/.github/workflows/build-push-docker.yml b/.github/workflows/build-push-docker.yml
--- a/.github/workflows/build-push-docker.yml
+++ b/.github/workflows/build-push-docker.yml
@@ -56,6 +56,19 @@ jobs:
               
     - uses: actions/checkout@v4
 
+    # If build_dir is empty or build_dir doesnt not contain all files: Dockerfile, task.* environment  fail
+    - name: Check build directory
+      run: |
+        if [ -z "${{ github.event.inputs.build_dir }}" ]; then
+          echo "Build directory is empty. Exiting."
+          exit 1
+        fi
+        if [ ! -f "${{ github.event.inputs.build_dir }}/${{ github.event.inputs.dockerfile }}" ]; then
+          echo "Dockerfile not found in the specified build directory. Exiting."
+          exit 1
+        fi
+      shell: bash
+
     - name: Login to container registry
       uses: docker/login-action@v3
       env:
